# Boreas Operator PM Agent 配置文件

# 服务器配置
server:
  host: "0.0.0.0"
  port: 8081

# 日志配置
log:
  level: "info"
  format: "json"
  output: "stdout"

# Agent 配置
agent:
  # Agent 唯一标识符
  id: "pm-node-1"

  # 主机名（可选，如果未设置会使用系统主机名）
  hostname: "pm-node-1.example.com"

  # 工作目录，用于存储应用状态和配置
  work_dir: "/var/lib/boreas-agent"

  # Docker 配置
  docker:
    # 是否启用 Docker 支持
    enabled: true

    # Docker Socket 路径
    socket_path: "/var/run/docker.sock"

    # Docker 镜像仓库地址（可选）
    registry: ""

    # 网络模式
    network_mode: "bridge"

  # 健康检查配置
  health:
    # 检查间隔（秒）
    check_interval: 30

    # 超时时间（秒）
    timeout: 10

    # 重试次数
    retry_count: 3

  # 自定义配置
  config:
    # 可以添加自定义的键值对配置
    # 例如：
    # custom_setting: "value"
    # another_setting: "another_value"
