version: '3.8'

services:
  # PostgreSQL 数据库
  postgres:
    image: postgres:15-alpine
    container_name: boreas-postgres
    environment:
      POSTGRES_DB: boreas
      POSTGRES_USER: boreas
      POSTGRES_PASSWORD: boreas123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    networks:
      - boreas-network

  # Redis 缓存
  redis:
    image: redis:7-alpine
    container_name: boreas-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - boreas-network

  # 管理服务
  management-service:
    build:
      context: .
      dockerfile: docker/management-service.Dockerfile
    container_name: boreas-management-service
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=boreas
      - DB_USER=boreas
      - DB_PASSWORD=boreas123
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - LOG_LEVEL=info
    depends_on:
      - postgres
      - redis
    networks:
      - boreas-network

  # 部署服务
  deploy-service:
    build:
      context: .
      dockerfile: docker/deploy-service.Dockerfile
    container_name: boreas-deploy-service
    ports:
      - "8081:8081"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=boreas
      - DB_USER=boreas
      - DB_PASSWORD=boreas123
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - LOG_LEVEL=info
    depends_on:
      - postgres
      - redis
    networks:
      - boreas-network

  # Webhook 服务
  webhook-service:
    build:
      context: .
      dockerfile: docker/webhook-service.Dockerfile
    container_name: boreas-webhook-service
    ports:
      - "8082:8082"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=boreas
      - DB_USER=boreas
      - DB_PASSWORD=boreas123
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - LOG_LEVEL=info
      - GITHUB_WEBHOOK_SECRET=your-webhook-secret
    depends_on:
      - postgres
      - redis
    networks:
      - boreas-network

  # Nginx 负载均衡器
  nginx:
    image: nginx:alpine
    container_name: boreas-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - management-service
      - deploy-service
      - webhook-service
    networks:
      - boreas-network

volumes:
  postgres_data:
  redis_data:

networks:
  boreas-network:
    driver: bridge
