version: '3.8'

services:
  # 基础设施服务
  postgres:
    image: postgres:15
    container_name: boreas-postgres
    environment:
      POSTGRES_DB: boreas
      POSTGRES_USER: boreas
      POSTGRES_PASSWORD: boreas123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    networks:
      - boreas-network

  redis:
    image: redis:7-alpine
    container_name: boreas-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - boreas-network

  # Master Service (核心服务)
  master-service:
    build:
      context: .
      dockerfile: deployments/docker/master-service.Dockerfile
    container_name: boreas-master-service
    ports:
      - "8080:8080"
    environment:
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=8080
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=boreas
      - DB_PASSWORD=boreas123
      - DB_NAME=boreas
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - LOG_LEVEL=info
    depends_on:
      - postgres
      - redis
    networks:
      - boreas-network
    volumes:
      - ./configs:/app/configs

  # Operator-K8s Service
  operator-k8s:
    build:
      context: .
      dockerfile: deployments/docker/operator-k8s.Dockerfile
    container_name: boreas-operator-k8s
    ports:
      - "8081:8081"
    environment:
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=8081
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=boreas
      - DB_PASSWORD=boreas123
      - DB_NAME=boreas
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - LOG_LEVEL=info
      - KUBECONFIG=/app/.kube/config
    depends_on:
      - postgres
      - redis
      - master-service
    networks:
      - boreas-network
    volumes:
      - ./configs:/app/configs
      - ~/.kube:/app/.kube:ro

  # Operator-PM Service
  operator-pm:
    build:
      context: .
      dockerfile: deployments/docker/operator-pm.Dockerfile
    container_name: boreas-operator-pm
    ports:
      - "8082:8082"
    environment:
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=8082
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=boreas
      - DB_PASSWORD=boreas123
      - DB_NAME=boreas
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - LOG_LEVEL=info
    depends_on:
      - postgres
      - redis
      - master-service
    networks:
      - boreas-network
    volumes:
      - ./configs:/app/configs
      - /var/run/docker.sock:/var/run/docker.sock

  # Web Management Interface
  web-management:
    build:
      context: .
      dockerfile: deployments/docker/web-management.Dockerfile
    container_name: boreas-web-management
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - REACT_APP_API_BASE_URL=http://localhost:8080
    depends_on:
      - master-service
    networks:
      - boreas-network


volumes:
  postgres_data:
  redis_data:

networks:
  boreas-network:
    driver: bridge