# 机器节点->IP地址映射配置文件
# 定义每个机器节点对应的IP地址，类似于 /etc/hosts 或 DNS 映射

# 节点名 -> IP地址的映射
node_to_ip:
  # 示例节点配置
  node-1: "192.168.1.10"
  node-2: "192.168.1.11"
  node-3: "192.168.1.12"
  node-4: "192.168.1.13"
  node-5: "192.168.1.14"
# 可以添加更多节点配置
# node-6: "192.168.1.15"
# node-7: "192.168.1.16"

# 注意：
# - IP地址格式：IPv4 地址（如 192.168.1.10）
# - 确保IP地址可达，Operator PM需要能够访问这些IP
# - 端口号在Agent服务配置中统一管理
