# Boreas Operator PM 配置文件

# 服务器配置
server:
  host: "0.0.0.0"
  port: 8080

# 数据库配置
database:
  host: "localhost"
  port: 5432
  user: "boreas"
  password: "boreas123"
  name: "boreas"
  ssl_mode: "disable"

# 日志配置
log:
  level: "info"
  format: "json"
  output: "stdout"

# 物理机管理配置
pm:
  # Agent 通信超时（秒）
  agent_timeout: 30

  # 最大重试次数
  max_retries: 3

  # 健康检查配置
  health_check:
    interval: 60 # 检查间隔（秒）
    timeout: 10 # 超时时间（秒）

  # 部署配置
  deployment:
    timeout: 300 # 部署超时（秒）
    max_concurrent: 5 # 最大并发部署数
    retry_interval: 30 # 重试间隔（秒）
    status_check: 30 # 状态检查间隔（秒）

  # Agent服务配置
  agent:
    port: 8081 # Agent服务端口
    path: "/v1" # Agent服务路径前缀

  # 配置文件路径配置
  config_paths:
    app_to_nodes: "./cmd/operator-pm/configs/app-to-nodes.yaml" # 应用->节点映射配置文件路径
    node_to_ip: "./cmd/operator-pm/configs/node-to-ip.yaml" # 节点->IP地址映射配置文件路径


  # 注意：应用->节点映射和节点->IP地址映射已移至独立配置文件
  # - app-to-nodes.yaml: 应用->机器节点映射
  # - node-to-ip.yaml: 机器节点->IP地址映射（类似于 /etc/hosts 或 DNS）
