# Boreas Operator PM 配置文件

# 服务器配置
server:
  host: "0.0.0.0"
  port: 8080

# 数据库配置
database:
  host: "localhost"
  port: 5432
  user: "boreas"
  password: "boreas123"
  name: "boreas"
  ssl_mode: "disable"

# 日志配置
log:
  level: "info"
  format: "json"
  output: "stdout"

# 物理机管理配置
pm:
  # Agent 通信超时（秒）
  agent_timeout: 30

  # 最大重试次数
  max_retries: 3

  # 健康检查配置
  health_check:
    interval: 60 # 检查间隔（秒）
    timeout: 10 # 超时时间（秒）

  # 部署配置
  deployment:
    timeout: 300 # 部署超时（秒）
    max_concurrent: 5 # 最大并发部署数
    retry_interval: 30 # 重试间隔（秒）
    status_check: 30 # 状态检查间隔（秒）

  # 自定义配置
  config:
    # 可以添加自定义的键值对配置
    # 例如：
    # custom_setting: "value"
