# Boreas Operator K8s 配置文件

# 服务器配置
server:
  host: "0.0.0.0"
  port: 8082

# 日志配置
log:
  level: "info"
  format: "json"
  output: "stdout"

# Kubernetes配置
k8s:
  # Kubernetes 配置文件路径（可选，默认使用集群内配置）
  config_path: ""

  # 默认命名空间
  namespace: "default"

  # Kubernetes 上下文（可选）
  context: ""

  # 操作超时（秒）
  timeout: 30

  # 重试次数
  retry_count: 3

  # 健康检查配置
  health_check:
    interval: 60 # 检查间隔（秒）
    timeout: 10 # 超时时间（秒）

  # 部署配置
  deployment:
    timeout: 300 # 部署超时（秒）
    max_concurrent: 5 # 最大并发部署数
    retry_interval: 30 # 重试间隔（秒）
    status_check: 30 # 状态检查间隔（秒）
    rollback_timeout: 180 # 回滚超时（秒）

  # 自定义配置
  config:
    # 可以添加自定义的键值对配置
    # 例如：
    # custom_setting: "value"
